# Site settings
title: "GO!"
description: "Página de redirecionamento."
baseurl: "" # the subpath of your site, e.g. /website
url: "" # the base hostname & protocol for your site e.g. http://rodrigo3d.com
lolipop-theme-color: "#ffffff" # Android Lolipop Theme Color


# User settings
author: Rodrigo Ribeiro - me@rodrigo3d.com
lang: pt_BR


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: [local]
  blanklines: false
  profile: false


# exclude my node related stuff
exclude: [
  'LICENSE',
  'README.md',
  'yarn.lock',
  'gulpfile.js',
  'package.json',
  'src',
  'node_modules',
  'desktop.ini',
  'Gemfile',
  'Gemfile.lock'
]


# include my node related stuff
include: [
  '_redirects'
]
